from django.urls import path
from .views import (
    admin_audit_logs_api,
    admin_health_api,
    admin_medical_data_api,
    admin_medical_versions_api,
    admin_overview_api,
    admin_restore_medical_version_api,
    admin_user_update_api,
    admin_users_api,
    chat_api,
    delete_session_api,
    change_password_api,
    csrf_api,
    get_chat_history,
    google_login_api,
    list_sessions_api,
    list_report_analyses_api,
    login_api,
    logout_api,
    me_api,
    mobile_token_login_api,
    mobile_token_logout_api,
    profile_api,
    report_analysis_detail_api,
    rename_session_api,
    register_api,
    analyze_report_api,
    settings_api,
)

urlpatterns = [
    path("auth/csrf/", csrf_api),
    path("auth/register/", register_api),
    path("auth/login/", login_api),
    path("auth/token-login/", mobile_token_login_api),
    path("auth/google/", google_login_api),
    path("auth/logout/", logout_api),
    path("auth/token-logout/", mobile_token_logout_api),
    path("auth/me/", me_api),
    path("auth/profile/", profile_api),
    path("auth/settings/", settings_api),
    path("auth/change-password/", change_password_api),
    path("sessions/", list_sessions_api),
    path("sessions/<int:session_id>/", delete_session_api),
    path("sessions/<int:session_id>/title/", rename_session_api),
    path("chat/", chat_api),
    path("history/<int:session_id>/", get_chat_history),
    path("reports/", list_report_analyses_api),
    path("reports/analyze/", analyze_report_api),
    path("reports/<int:report_id>/", report_analysis_detail_api),
    path("admin/overview/", admin_overview_api),
    path("admin/users/", admin_users_api),
    path("admin/users/<int:user_id>/", admin_user_update_api),
    path("admin/medical-data/", admin_medical_data_api),
    path("admin/medical-data/versions/", admin_medical_versions_api),
    path("admin/medical-data/restore/<int:version_id>/", admin_restore_medical_version_api),
    path("admin/health/", admin_health_api),
    path("admin/audit-logs/", admin_audit_logs_api),
]
